### ISSUE TITLE
imp

### ISSUE THREAD

**Issue by Habeel06** [meesam4687/website-backend#2]
keep it private as its specifically for cc.

**Comment by meesam4687** [comment]
> keep it private as its specifically for cc.

accidentally uploaded here
main on the org and no need to keep it private since no confidential info here

**Comment by meesam4687** [comment]
> keep it private as its specifically for cc.

accidentally uploaded here
main on the org and no need to keep it private since no confidential info here

**Comment by meesam4687** [comment]
> keep it private as its specifically for cc.

accidentally uploaded here
main on the org and no need to keep it private since no confidential info here
